chore: trigger ci check

diff --git a/.github/workflows/lint-check.yml b/.github/workflows/lint-check.yml
--- a/.github/workflows/lint-check.yml
+++ b/.github/workflows/lint-check.yml
@@ -11,10 +11,6 @@ concurrency:
 jobs:
   spotless:
     runs-on: "ubuntu-latest"
-    permissions:
-      checks: "write"
-      contents: "read"
-      pull-requests: "write"
     steps:
     - name: "Checkout code"
       uses: "actions/checkout@v4"
@@ -32,18 +28,16 @@ jobs:
         restore-keys: "${{ runner.os }}-gradle-"
 
 
+
     - name: "Run Spotless check"
-      id: "spotless-check"
-      run: "./gradlew spotlessCheck"
-      continue-on-error: true
+      run: "./gradlew spotlessCheck || echo 'FAILED=true' >> $GITHUB_ENV"
     - name: "Comment on PR if format fails"
-      if: "failure() && steps.spotless-check.outcome == 'failure'"
+      if: "env.FAILED == 'true'"
       uses: "marocchino/sticky-pull-request-comment@v2.9.4"
       with:
         header: "format-check"
-        message: "❌ Spotless formatting check failed in one or more modules.\n\nRun\
-          \ the following command locally to auto-fix:\n```bash\n./gradlew spotlessApply\n\
-          ```\n\nThen commit & push the changes to update this PR ✅\n"
-    - name: "Fail job if Spotless check failed"
-      if: "steps.spotless-check.outcome == 'failure'"
+        message: "❌ Spotless formatting check failed.\n\nRun this command to fix:\n\
+          ```bash\n./gradlew spotlessApply\n```\n"
+    - name: "Fail if needed"
+      if: "env.FAILED == 'true'"
       run: "exit 1"
